---
- name: Add tailscale apt key.
  apt_key:
    url: "{{ tailscale_apt_key }}"
    state: present
  ignore_errors: "{{ tailscale_apt_ignore_key_error }}"

- name: Add tailscale repository.
  apt_repository:
    repo: "{{ tailscale_apt_repository }}"
    state: present
    update_cache: true

- name: Install tailscale.
  apt:
    name: tailscale
    state: present

- name: Ensure tailscaled is running as desired.
  service:
    name: tailscaled
    state: "{{ tailscale_daemon_state }}"
    enabled: "{{ tailscale_daemon_enabled }}"

# The reason to read the auth key from stdin is to avoid leaking the key in
# the logs. If ANSIBLE_DEBUG=1, then stdin is logged along with the auth key.
- name: Connect to the network with tailscale up.
  become: true
  command: |
    tailscale up --authkey=file:/dev/stdin {{ tailscale_up_args | join(' ') }}
  args:
    stdin: "{{ tailscale_up_auth_key }}"
  async: "{{ tailscale_up_command_timeout }}"
  poll: 1
  when:
    - not ( tailscale_skip_up | bool )
  tags:
    - molecule-idempotence-notest
