---
- name: Add tailscale apt key.
  apt_key:
    url: "{{ tailscale_apt_key }}"
    state: present
  ignore_errors: "{{ tailscale_apt_ignore_key_error }}"

- name: Add tailscale repository.
  apt_repository:
    repo: "{{ tailscale_apt_repository }}"
    state: present

- name: Install tailscale.
  apt:
    name: tailscale
    state: present

- name: Create the default config file.
  copy:
    content: "{{ tailscale_config_contents }}"
    dest:  "/etc/default/tailscaled"
    user:  "root"
    group: "root"
    mode:  "0644"

- name: Ensure tailscaled is running as desired.
  service:
    name: tailscaled
    state: "{{ tailscale_service_state }}"
    enabled: "{{ tailscale_service_enabled }}"

- include_tasks: run_up.yml
  when: tailscale_run_up_command | bool
