---
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Install Tailscale.
  package:
    name: tailscale
    state: present

- name: Ensure service is running as desired.
  service:
    name: "{{ tailscale_service_name }}"
    state: "{{ tailscale_service_state }}"
    enabled: "{{ tailscale_service_enabled }}"

- include_tasks: register.yml
  when: tailscale_register_node | bool

- name: Configure options in /etc/default/tailscaled.
  lineinfile:
    dest: /etc/default/tailscaled
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: EOF
    state: present
  with_items: "{{ tailscale_default_tailscaled_options }}"
  notify: restart tailscaled

- include_tasks: generate-cert.yml
  when: tailscale_generate_cert | bool
