---
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Install Tailscale.
  package:
    name: tailscale
    state: present

- name: Ensure service is running as desired.
  service:
    name: "{{ tailscale_service_name }}"
    state: "{{ tailscale_service_state }}"
    enabled: "{{ tailscale_service_enabled }}"

- include_tasks: register.yml
  when: tailscale_register_node | bool

- include_tasks: configure-default-options.yml
  when: tailscale_configure_default_options | bool

# Read /etc/default/tailscaled before proceeding
- meta: flush_handlers

- include_tasks: cert.yml
  when: tailscale_cert_enabled | bool
