---
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Tailscale.
  package:
    name: tailscale
    state: present

- name: Ensure service is running as desired.
  service:
    name: "{{ tailscale_service_name }}"
    state: "{{ tailscale_service_state }}"
    enabled: "{{ tailscale_service_enabled }}"

- include_tasks: register.yml
  when: tailscale_register_node | bool
