---
- name: Add tailscale apt key.
  apt_key:
    url: "{{ tailscale_apt_key }}"
    state: present
  ignore_errors: "{{ tailscale_apt_ignore_key_error }}"

- name: Add tailscale repository.
  apt_repository:
    repo: "{{ tailscale_apt_repository }}"
    state: present
    update_cache: true

- name: Install tailscale.
  apt:
    name: tailscale
    state: present

- name: Ensure tailscaled is running as desired.
  service:
    name: tailscaled
    state: "{{ tailscale_daemon_state }}"
    enabled: "{{ tailscale_daemon_enabled }}"

- include_tasks: run_up.yml
  when: tailscale_run_up_command | bool
