---
- name: Assert that tailscale_register_authkey is not empty.
  assert:
    that:
      - tailscale_register_authkey | length > 0
    quiet: true

- name: Register the node.
  command: |
    tailscale up --authkey="{{ tailscale_register_authkey }}" --timeout="{{ tailscale_register_timeout }}" {{ tailscale_register_args }}
  tags:
    - molecule-idempotence-notest
