---
- name: Assert that tailscale_up_auth_key is not empty.
  assert:
    that:
      - tailscale_up_auth_key | length > 0
    quiet: true

# The reason to read the auth key from stdin is to avoid leaking the key in
# the logs. If ANSIBLE_DEBUG=1, then stdin is logged along with the auth key.
- name: Connect to the network with tailscale up.
  become: true
  command: |
    tailscale up --authkey=file:/dev/stdin {{ tailscale_up_args | join(' ') }}
  args:
    stdin: "{{ tailscale_up_auth_key }}"
  async: "{{ tailscale_up_command_timeout }}"
  poll: 1
  tags:
    - molecule-idempotence-notest
