---
- name: Assert that tailscale_up_authkey is not empty.
  assert:
    that:
      - tailscale_up_authkey | length > 0
    quiet: true

- name: Assert that tailscale_up_timeout is not empty.
  assert:
    that:
      - tailscale_up_timeout | length > 0
    quiet: true

- name: Run tailscale up and join tailnet.
  command: |
    tailscale up --authkey="{{ tailscale_up_authkey }}" --timeout="{{ tailscale_up_timeout }}" {{ tailscale_up_extra_args }}
  tags:
    - molecule-idempotence-notest
  no_log: "{{ tailscale_up_no_log }}"
