---
- name: Assert that tailscale_up_authkey is not empty.
  assert:
    that:
      - tailscale_up_authkey | length > 0
    quiet: true

- name: Assert that tailscale_up_timeout is not empty.
  assert:
    that:
      - tailscale_up_timeout | length > 0
    quiet: true

- name: Get tailscale status before running up.
  command: |
    tailscale status --json
  register: tailscale_status_before_up
  changed_when: false

- name: Display tailscale status before up.
  debug:
    var: tailscale_status_before_up.stdout
  when: tailscale_debug

# Up - V1
# - name: Run tailscale up.
#   command: |
#     tailscale up --authkey="{{ tailscale_up_authkey }}" --timeout="{{ tailscale_up_timeout }}" {{ tailscale_up_extra_args }}
#   tags:
#     - molecule-idempotence-notest
#   no_log: "{{ tailscale_up_no_log }}"

# Improved version that properly detects changes by comparing tailscale status before and after.
#
# The previous version always reported changes even when tailscale was already connected.
# This version compares BackendState, UserID, and TailscaleIPs from before/after status to determine
# if the up command actually changed the tailscale state.
#
# The up command output is redirected to stderr so any errors can be inspected while
# allowing status JSON to be captured in stdout for comparison.
#
# Up - V2
- name: Run tailscale up.
  shell: |
    >&2 tailscale up --authkey="{{ tailscale_up_authkey }}" --timeout="{{ tailscale_up_timeout }}" {{ tailscale_up_extra_args }}
    tailscale status --json
  no_log: "{{ tailscale_up_no_log }}"
  register: tailscale_status_after_up
  changed_when: >
    (tailscale_status_before_up.stdout | from_json).BackendState != (tailscale_status_after_up.stdout | from_json).BackendState or
    (tailscale_status_before_up.stdout | from_json).Self.UserID != (tailscale_status_after_up.stdout | from_json).Self.UserID or
    (tailscale_status_before_up.stdout | from_json).Self.TailscaleIPs != (tailscale_status_after_up.stdout | from_json).Self.TailscaleIPs
  failed_when: >
    (tailscale_status_after_up.stdout | from_json).BackendState == "NoState" or
    (tailscale_status_after_up.stdout | from_json).BackendState == "NeedsLogin" or
    (tailscale_status_after_up.stdout | from_json).BackendState == "NeedsMachineAuth" or
    (tailscale_status_after_up.stdout | from_json).BackendState == "Stopped"

- name: Display tailscale status after up.
  debug:
    var: tailscale_status_after_up.stdout
  when: tailscale_debug
