---
# TODO: serve and funnel command line arguments have changed.
# See https://tailscale.com/blog/reintroducing-serve-funnel/.

- name: Converge
  hosts: all
  become: true

  vars:
    tailscale_up_node: true
    tailscale_up_authkey: "{{ lookup('env', 'TAILSCALE_AUTHKEY') }}"
    tailscale_up_extra_args: "--accept-routes --hostname=gh-actions-ts-serve-{{ lookup('env', 'HOSTNAME') }}-{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version|lower }}-{{ ansible_architecture|replace('_', '-') }}"
    tailscale_serve_enabled: true
    tailscale_serve_content:
      - "http / text:'Hello, world!'"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false
      when: ansible_os_family == 'Debian'

    - name: Wait for systemd to complete initialization.  # noqa 303
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

  roles:
    - role: jason_riddle.tailscale

  post_tasks:
    - name: Verify tailscale is installed.
      command: tailscale --version
      changed_when: false

    - name: Get tailscale status.
      command: tailscale status --peers=false
      changed_when: false
      register: tailscale_status

    - name: Print tailscale status.
      debug: var=tailscale_status.stdout
