---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false
      when: ansible_os_family == 'Debian'

    - name: Install gnupg (Debian).
      apt: name=gnupg state=present
      when: ansible_os_family == 'Debian'

  roles:
    - role: jason-riddle.tailscale

  post_tasks:
    - name: Verify tailscale is installed.
      command: tailscale --version
      changed_when: false
