---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false
      when: ansible_os_family == 'Debian'

    - name: Wait for systemd to complete initialization.  # noqa 303
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

  roles:
    - role: jason_riddle.tailscale

  post_tasks:
    - name: Verify tailscale is installed.
      command: tailscale --version
      changed_when: false

    - name: Get tailscale status.
      command: tailscale status --peers=false
      changed_when: false
      # tailscale status returns a non-zero exit code when logged-out. So a
      # simple workaround is just ignore all error codes and assume it
      # installed correctly
      ignore_errors: true
      register: tailscale_status

    - name: Print tailscale status.
      debug: var=tailscale_status.stdout
