---
name: CI - Molecule

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  TAILSCALE_AUTHKEY: "${{ secrets.TAILSCALE_AUTHKEY }}"

defaults:
  run:
    working-directory: 'jason_riddle.tailscale'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: debian10 # Buster
            playbook: converge.yml
          - distro: ubuntu1804 # Bionic Beaver
            playbook: converge.yml
          # TODO: Failed to get D-Bus connection: No such file or directory
          # - distro: centos7
          #   playbook: converge.yml
          - distro: centos8
            playbook: converge.yml

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'jason_riddle.tailscale'

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] docker

      - name: Set HOSTNAME.
        run: echo "HOSTNAME=$(cat /etc/hostname)" >> $GITHUB_ENV

      - name: Run Molecule tests.
        run: |
          molecule test --scenario-name default
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_LOAD_CALLBACK_PLUGINS: true
          ANSIBLE_STDOUT_CALLBACK: 'yaml'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_PLAYBOOK: ${{ matrix.playbook }}
